### ISSUE TITLE
Problem when i run Python3 bot.py

### ISSUE THREAD

**Issue by diasostis** [lucasvianav/instagram-raffle#1]
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    creds = ServiceAccountCredentials.from_json_keyfile_name("credentials.json", scope)
  File "/home/diasostis/.local/lib/python3.8/site-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

**Comment by lucasvianav** [comment]
In order to run the bot you must provide your own credentials.json to access the Google Sheets API, as well as your own sheet - you can learn more about that in [this video](https://www.youtube.com/watch?v=cnPlKLEGR7E).
